Add `isJsonContentType` predicate to `fetchBaseQuery`
reduxjs/redux-toolkit pull request #2331
Opened 2022-05-15 19:21 UTC by msutkowski

2022-05-16 14:01 UTC, ShaunDychko requested changes

2022-05-16 14:01 UTC, ShaunDychko commented on packages/toolkit/src/query/fetchBaseQuery.ts
> +   * const isJsonContentType = (headers: Headers) => ["application/vnd.api+json", "application/json"].includes(headers.get("content-type")?.trim());
```suggestion
   * const isJsonContentType = (headers: Headers) => ["application/vnd.api+json", "application/json", "application/vnd.hal+json"].includes(headers.get("content-type")?.trim());
```

2022-05-16 14:01 UTC, ShaunDychko commented on packages/toolkit/src/query/fetchBaseQuery.ts
> +   * const isJsonContentType = (headers: Headers) => ["application/vnd.api+json", "application/json"].includes(headers.get("content-type")?.trim());
Document adding a media type not already included by default.

2022-05-19 03:31 UTC, msutkowski commented on packages/toolkit/src/query/fetchBaseQuery.ts
> +   * By default, we only check for 'application/json' as the content-type for json. If you need to support another format, you can pass
I'm not opposed to doing this, but I'd prefer to have @phryneas and @markerikson chime in. We originally based this on how axios/redaxios work (if no headers set and it looks like json, make it json and stringify). If you were to use axios or anything, you'd create an instance and set your default headers on each request, the same as you'd need to do with this proposal. I'm not so sure we should operate any differently, but I could be wrong!

2022-06-10 14:50 UTC, merged