Contributing Markdown Refresh
reduxjs/redux-toolkit pull request #4139
Opened 2024-01-30 11:34 UTC by itz-Me-Pj

Updated Contributing.md file to be more beginner friendly for contributions.

2024-01-30 12:53 UTC, EskiMojo14 requested changes

2024-01-30 12:53 UTC, EskiMojo14 commented on CONTRIBUTING.md
> +Please be considerate when doing this as this is not the primary purpose of the issue tracker.
i don't agree with this - they should either open a discussion or try the reactiflux  #redux channel, not use the issue tracker

2024-01-30 12:53 UTC, EskiMojo14 commented on CONTRIBUTING.md
> +On both websites, it is a good idea to structure your code and question in a way that is easy to read to entice people to answer it. For example, we encourage you to use syntax highlighting, indentat
```suggestion
On both websites, it is a good idea to structure your code and question in a way that is easy to read to help people to answer it. For example, we encourage you to use syntax highlighting, indentation, and split text in paragraphs.
```

2024-01-30 12:53 UTC, EskiMojo14 commented on CONTRIBUTING.md
> +We use the [Issue tracker](https://github.com/reduxjs/redux-toolkit/issues) to keep track of bugs and improvements to redux-toolkit itself, its examples, and the documentation. We encourage you to op
```suggestion
We use the [Issue tracker](https://github.com/reduxjs/redux-toolkit/issues) to keep track of bugs and improvements to Redux Toolkit itself, its examples, and the documentation. We encourage you to open issues to discuss improvements, architecture, theory, internal implementation, etc. If a topic has been discussed before, we will ask you to join the previous discussion.
```

2024-01-30 12:53 UTC, EskiMojo14 commented on packages/toolkit/README.md
> +Pls refer to our [contributing guide](/CONTRIBUTING.md) to learn about our development process, how to propose bugfixes and improvements, and how to build and test your changes to Redux-toolkit.
```suggestion
Please refer to our [contributing guide](/CONTRIBUTING.md) to learn about our development process, how to propose bugfixes and improvements, and how to build and test your changes to Redux Toolkit.
```

2024-01-30 13:17 UTC, itz-Me-Pj commented on CONTRIBUTING.md
> +Please be considerate when doing this as this is not the primary purpose of the issue tracker.
@EskiMojo14 
Some questions take a long time to get an answer. If your question gets closed or you don't get a reply on StackOverflow for longer than a few days, we encourage you to either open a discussion or try the reactiflux (#redux channel) on discord our redux community will help you resolving the issue.
How does this sound?

2024-01-30 22:00 UTC, EskiMojo14 commented on CONTRIBUTING.md
> +Please be considerate when doing this as this is not the primary purpose of the issue tracker.
yeah, i think:
```suggestion
If your question gets closed or you don't get a reply after a few days, consider opening a [discussion](https://github.com/reduxjs/redux-toolkit/discussions) or joining the [Reactiflux](https://discord.gg/reactiflux) discord server and asking in the #redux channel.
```

2024-01-31 00:42 UTC, itz-Me-Pj commented
@EskiMojo14 all the requested changes have been made successfully. 
Do you want me to update the code of conduct doc as well, as it hasn't been updated since a long time and currently the redux code of conduct is following code covenant version 1.4  where as the toolkit is at 1.0?
Also I can add ways you can contribute in the contribution doc by referring them to the right doc folder or the right example folder or the right development block for making successful contributions.

2024-01-31 12:30 UTC, EskiMojo14 commented on packages/toolkit/README.md
> +## Contributing
re-reading this, i think it should be moved to the end of the readme, after the sections about what it's for and what it includes

2024-01-31 12:35 UTC, EskiMojo14 commented
code of conduct i don't really know about - for now i think it should be left as is.

i don't really understand what you mean regarding referring to the "correct doc folder" etc

2024-02-01 01:28 UTC, itz-Me-Pj commented
@EskiMojo14 by referring to doc or example folder I meant to add something like:-
**Ways you can contribute**
There are several ways you can contribute to the repository instead of developing a feature or fixing a bug you can contribute by updating the [documentation](https://github.com/reduxjs/redux-toolkit/tree/master/docs) for a specific feature or implementation. Or, you can add [examples](https://github.com/reduxjs/redux-toolkit/tree/master/examples) of any 3rd party implementation like graphQL or React (just an example).

2024-02-02 17:32 UTC, EskiMojo14 commented
sure, can't hurt - those sentences are quite long so some punctuation would be good but otherwise what you have there is fine

2024-02-02 19:13 UTC, itz-Me-Pj commented
@EskiMojo14 Added the final changes to the contribution doc. Pls review and tell if anything else is left to add.
Also I was thinking to work on rewriting the documentation in [issues](https://github.com/reduxjs/redux/issues?page=1&q=is%3Aissue+is%3Aopen) that are open since a long time in the core redux repo. Pls have a look and suggest if they can be worked upon or not.

2024-02-03 14:03 UTC, merged

2024-02-03 14:04 UTC, EskiMojo14 commented
thanks!

with regards to core docs, i would need to know specifically which one you want to write, but generally if it's still open we'd welcome a PR for it