[entityAdapter] handle draft states in selectors
reduxjs/redux-toolkit pull request #815
Opened 2020-11-19 21:03 UTC by phryneas

Closes #606.

@markerikson what are your thoughts on exporting `createDraftSafeSelector`?

2020-11-19 21:09 UTC, markerikson commented
That I could live with.

Y'know, I'm really starting to lose track of all the stuff we _do_ export from RTK... :)

2020-11-19 21:10 UTC, phryneas commented
Note to self: export that thing *and* add that to the docs. Tomorrow :)

That TODO list for 1.5.0 is getting shorter and shorter though :)

2020-11-21 17:43 UTC, phryneas commented
@markerikson any comments on the docs for this one? :)

2020-11-21 19:29 UTC, msutkowski reviewed
Looks good! I just have a couple questions on descriptions

2020-11-21 19:29 UTC, msutkowski commented on docs/api/createSelector.mdx
> +can be used in the context of `createReducer` and `createSlice` reducers with mutable logic.
Should we explicitly state extra reducers as well?

2020-11-21 19:29 UTC, msutkowski commented on docs/api/createSelector.mdx
> +Besides re-exporting `createSelector`, RTK also exports a wrapped version of `createSelector` named `createDraftSafeSelector` that allows you to create selectors that
Do we need to explain what/why in regards to immer Drafts or link to what isDraftable even is? I think the description you have in the code would actually work well here for clarity.

2020-11-27 23:48 UTC, markerikson requested changes

2020-11-28 18:41 UTC, merged